//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotosWCF
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class File
    {
        [DataMember]
        public int FileID { get; set; }

        [DataMember]
        public string FileName { get; set; }

        [DataMember]
        public string FileDesc { get; set; }

        [DataMember]
        public string FileType { get; set; }

        [DataMember]
        public string FileSize { get; set; }

        [DataMember]
        public string FilePath { get; set; }

        [DataMember]
        public string FileTags { get; set; }

        [DataMember]
        public string FileDate { get; set; }

        [DataMember]
        public int FolderId { get; set; }

        [DataMember]
        public virtual Folder Folder { get; set; }
    }
}
